---
- name: sets up a samba server
  hosts: servers
# remote_user: citsalud
  become: true
  vars_files: variables.yaml

  tasks:

  - name: sets hostname for mdns
    hostname:
      name: citsaludserver

  #######################################################
  #################        <APT>        #################
  #######################################################

  - name: installs samba smb server and ufw firewall
    apt:
      name:
        - samba
        - ufw
        - iptables
        - fail2ban
        - network-manager
        - openssh-server
        - avahi-daemon
        - autossh

  - name: updates the packages
    apt:
      update_cache: yes
      upgrade: full
      autoclean: yes
      autoremove: yes
      purge: yes

  #######################################################
  #################       </APT>        #################
  #######################################################


  #######################################################
  #################        <UFW>        #################
  #######################################################

  - name: cleans ufw to default
    community.general.ufw:
      state: reset

  - name: configures ufw to block everithing silently
    community.general.ufw:
      default: deny

  - name: configures ufw to allow ssh (more security will be added by using public key auth)
    community.general.ufw:
      rule: allow
      name: OpenSSH

  - name: configures ufw to allow samba on localhost
    community.general.ufw:
      rule: allow
      name: Samba
      from_ip: 127.0.0.1
      to_ip: 127.0.0.1

  - name: configures ufw to allow samba on 192.168.x.x
    community.general.ufw:
      rule: allow
      name: Samba
      from_ip: 192.168.0.0/16
      to_ip: 192.168.0.0/16

  - name: configures ufw to allow samba on 172.0xx.x.x
    community.general.ufw:
      rule: allow
      name: Samba
      from_ip: 172.16.0.0/12
      to_ip: 172.16.0.0/12

  - name: configures ufw to allow samba on 10.x.x.x
    community.general.ufw:
      rule: allow
      name: Samba
      from_ip: 10.0.0.0/8
      to_ip: 10.0.0.0/8

  - name: configures ufw to allow samba on RCF 4193
    community.general.ufw:
      rule: allow
      name: Samba
      from_ip: "fc00::/7"
      to_ip: "fc00::/7"

  - name: configures ufw to allow samba on RFC 3879
    community.general.ufw:
      rule: allow
      name: Samba
      from_ip: "fec0::/10"
      to_ip: "fec0::/10"

  - name: enables ufw
    community.general.ufw:
      state: enabled

  - name: reloads ufw
    community.general.ufw:
      state: reloaded

  #######################################################
  #################       </UFW>        #################
  #######################################################

  #######################################################
  #################       <SAMBA>       #################
  #######################################################

  - name: creates a group to be able to view and edit the folders
    group:
      name: citsaludusers

  - name: creates a folder in the root. this is the directory for the primary samba folders
    file:
      path: /smbcitsalud
      group: citsaludusers
      state: directory
      mode: 0770
      recurse: yes

  - name: creates a folder in the root. this is the directory for an hdd mirror backup
    file:
      path: /smbmirror
      group: citsaludusers
      state: directory
      mode: 0770
      recurse: yes

  - name: creates a user for the department abastecimiento
    user:
      name: abastecimiento
      append: yes
      groups:
        - citsaludusers
      password: $6$S/tRb70cHZ/tn9/P$QI5GA2lESw86lIdHHTReLlfOMzEVYAKMM8iwvmHyOEe0gBqJNoBoBjbJGbt/N26D5udM0xrjBpsk5dKRzBkDS.
      create_home: no

  - name: creates a folder for the aforementioned user to be smb shared
    file:
      path: /smbcitsalud/abastecimiento
      owner: abastecimiento
      group: citsaludusers
      state: directory
      mode: 0770
      recurse: yes

  - name: creates a user for the department contabilidad
    user:
      name: contabilidad
      append: yes
      groups:
        - citsaludusers
      password: $6$1Ssh1no4gd7Uuvf7$ZjJksQ3V/SRZUq8D35x0zzWlsOKMZvDb3ejtL49znHJmj1kHfnVLJTWaNZpeuW0nCoDt4vDeREtpHLBSKelI9/
      create_home: no

  - name: creates a folder for the aforementioned user to be smb shared
    file:
      path: /smbcitsalud/contabilidad
      owner: contabilidad
      group: citsaludusers
      state: directory
      mode: 0770
      recurse: yes

  - name: creates a user for the department imagenologia
    user:
      name: imagenologia
      append: yes
      groups:
        - citsaludusers
      password: $6$YgNIsyGTAg/faca7$i.Qc0A/W68cuKR6ZC0OdITlQIoKVBrN/IAYovpFZ23RPIimMUKh3J2x4sxx.S7XnkiM4B8AA7v.c9bdyLyNoO1
      create_home: no

  - name: creates a folder for the aforementioned user to be smb shared
    file:
      path: /smbcitsalud/imagenologia
      owner: imagenologia
      group: citsaludusers
      state: directory
      mode: 0770
      recurse: yes

  - name: creates a user for the department kinesiologia
    user:
      name: kinesiologia
      append: yes
      groups:
        - citsaludusers
      password: $6$HZWrnp1wWOQBFFRM$tCAi2hvCLA76h5aC9IoAq7W/aBSg8QiUeAZY9j5guREZgTqCwYBlclcXeEoktrh2Q3L2oIoPmd9E0wyskQoG0/
      create_home: no

  - name: creates a folder for the aforementioned user to be smb shared
    file:
      path: /smbcitsalud/kinesiologia
      owner: kinesiologia
      group: citsaludusers
      state: directory
      mode: 0770
      recurse: yes

  - name: creates a user for the department recursoshumanos
    user:
      name: recursoshumanos
      append: yes
      groups:
        - citsaludusers
      password: $6$3QM1d58jZv5q3pHp$Ose2JqAI4fuHzvOSrtQ10xyuDx1mNnFv.TSBA6p7qBMd0TBE7VG0XtpVF5PKraTkGgZq2ydnpYtIvACvXdEuT1
      create_home: no

  - name: creates a folder for the aforementioned user to be smb shared
    file:
      path: /smbcitsalud/recursoshumanos
      owner: recursoshumanos
      group: citsaludusers
      state: directory
      mode: 0770
      recurse: yes

  - name: creates a user for the company admin
    user:
      name: admin
      append: yes
      groups:
        - citsaludusers
      password: $6$C2tJ9A0k48V.Ula7$cVMaA64zdmy2AE.efJFdAF8qFCahh7Qu1msd6q5lTT8EUw863.V7/ZHb2IetOewLhqV5ortCkePRH5pPWA9yP0
      create_home: no

  - name: creates a folder for the aforementioned user to be smb shared
    file:
      path: /smbcitsalud/admin
      owner: admin
      group: citsaludusers
      state: directory
      mode: 0770
      recurse: yes

  - name: creates a user for techical support with sudo access
    user:
      name: soporte
      append: yes
      groups:
        - citsaludusers
        - sudo
      password: $6$G0TABL01gyipijbF$demVH8eo/Ofjoal1iUQPB7vv62LqlA2XVExwh4VfxThALWaoUa8bLqcYMlZctinbk49TyJRcZYLHdlMOsbV1r0
      create_home: yes
      shell: /bin/bash

  - name: creates a user for a guest
    user:
      name: invitado
      append: yes
      groups:
        - citsaludusers
      password: $6$4hd5VnPeOt2uRPsh$HNQWfX2JbzEFQ.bz/wTDXepASWw8ifycfjckKBnTEV1InFVHlwyNePBcYispjNHr.eqBFafFOsGOAynqXAUPb/
      create_home: no

  - name: adds the smb config 
    copy:
      src: ./smb.conf
      dest: /etc/samba/smb.conf
      force: yes
      mode: 0644
  
  - name: restarts the samba service
    service:
      name: sshd
      enabled: yes
      state: restarted
  #######################################################
  #################      </SAMBA>       #################
  #######################################################

  #######################################################
  #################        <SSH>        #################
  #######################################################

  - name: adds the access ssh key from this pc to the user with sudo access
    ansible.posix.authorized_key:
      user: soporte
      state: present
      key: "{{ lookup('file', '~/.ssh/soporte.pub') }}"

  - name: "adds ssh key on de sudo user without passphrase (be careful where do you put this on)"
    community.crypto.openssh_keypair:
      path: /home/soporte/.ssh/id_ed25519
      type: ed25519
      force: no
  - name: chowns the private key to the user
    file:
      path: /home/soporte/.ssh/id_ed25519
      owner: soporte
      group: soporte
      mode: 0400
  - name: chowns the public key to the user
    file:
      path: /home/soporte/.ssh/id_ed25519.pub
      owner: soporte
      group: soporte
      mode: 0400


  #######################################################
  #################       </SSH>        #################
  #######################################################

  - name: final messages
    debug:
      msg: |
          YOU WILL NEED TO MANUALLY
          -> smbpasswd TO EVERY USER
          -> create an anchor user with uid 999 to reverse ssh
          
