---
- name: "SSH KEYS ON SUPPORT ACCOUNT"
  hosts: servers
# remote_user: citsalud
  become: true

  tasks:

  - name: adds the access ssh key from this pc to the user with sudo access
    ansible.posix.authorized_key:
      user: soporte
      state: present
      key: "{{ lookup('file', '~/.ssh/soporte.pub') }}"

  - name: "adds ssh key on de sudo user without passphrase (be careful where do you put this on)"
    community.crypto.openssh_keypair:
      path: /home/soporte/.ssh/soporte
      comment: citsalud-soporte
      type: ed25519
      force: no
      owner: soporte
      group: soporte
      mode: 0400

  - name: fetches the pubkey and copies it to here
    fetch:
      src: /home/soporte/.ssh/soporte.pub
      fail_on_missing: yes
      dest: ./../../
      flat: yes

