---
- name: " generates access keys locally for the user {{ lookup('env', 'USER') }} for later accessing remote"
  hosts: localhost
  connection: local
  become: false
  vars_prompt:
  - name: "ssh_passphrase"
    prompt: "Enter the passphrase for the SSH key"

  tasks:

  - name: generates a ssh key for accessing the remote computers later
    community.crypto.openssh_keypair:
      path: ~/.ssh/soporte
      type: ed25519
      force: no
      owner: "{{ lookup('env', 'USER') }}"
      group: "{{ lookup('env', 'USER') }}"
      mode: 0400
      passphrase: "{{ ssh_passphrase }}"
      comment: "soporte"

  - name: "adds the ssh key on the config. Test for line"
    shell: grep -c ".*soporte.*" ~/.ssh/config  || true
    register: test_grep

  - name: "adds tested line. completing the config for use"
    lineinfile:
      dest: ~/.ssh/config
      line: IdentityFile ~/.ssh/soporte
    when: test_grep.stdout == "0"

