---
- name: "SAMBA AND USERS"
  hosts: servers
# remote_user: citsalud
  become: true

  tasks:

  - name: creates a group to be able to view and edit the folders
    group:
      name: citsaludusers

  - name: creates a folder in the root. this is the directory for the primary samba folders
    file:
      path: /smbcitsalud
      group: citsaludusers
      state: directory
      mode: 0770
      recurse: yes

  - name: creates a folder in the root. this is the directory for an hdd mirror backup
    file:
      path: /smbmirror
      group: citsaludusers
      state: directory
      mode: 0770
      recurse: yes

  - name: creates a user for the department abastecimiento
    user:
      name: abastecimiento
      append: yes
      groups:
        - citsaludusers
      password: $6$S/tRb70cHZ/tn9/P$QI5GA2lESw86lIdHHTReLlfOMzEVYAKMM8iwvmHyOEe0gBqJNoBoBjbJGbt/N26D5udM0xrjBpsk5dKRzBkDS.
      create_home: no

  - name: creates a folder for the aforementioned user to be smb shared
    file:
      path: /smbcitsalud/abastecimiento
      owner: abastecimiento
      group: citsaludusers
      state: directory
      mode: 0770
      recurse: yes

  - name: creates a user for the department contabilidad
    user:
      name: contabilidad
      append: yes
      groups:
        - citsaludusers
      password: $6$1Ssh1no4gd7Uuvf7$ZjJksQ3V/SRZUq8D35x0zzWlsOKMZvDb3ejtL49znHJmj1kHfnVLJTWaNZpeuW0nCoDt4vDeREtpHLBSKelI9/
      create_home: no

  - name: creates a folder for the aforementioned user to be smb shared
    file:
      path: /smbcitsalud/contabilidad
      owner: contabilidad
      group: citsaludusers
      state: directory
      mode: 0770
      recurse: yes

  - name: creates a user for the department imagenologia
    user:
      name: imagenologia
      append: yes
      groups:
        - citsaludusers
      password: $6$YgNIsyGTAg/faca7$i.Qc0A/W68cuKR6ZC0OdITlQIoKVBrN/IAYovpFZ23RPIimMUKh3J2x4sxx.S7XnkiM4B8AA7v.c9bdyLyNoO1
      create_home: no

  - name: creates a folder for the aforementioned user to be smb shared
    file:
      path: /smbcitsalud/imagenologia
      owner: imagenologia
      group: citsaludusers
      state: directory
      mode: 0770
      recurse: yes

  - name: creates a user for the department kinesiologia
    user:
      name: kinesiologia
      append: yes
      groups:
        - citsaludusers
      password: $6$HZWrnp1wWOQBFFRM$tCAi2hvCLA76h5aC9IoAq7W/aBSg8QiUeAZY9j5guREZgTqCwYBlclcXeEoktrh2Q3L2oIoPmd9E0wyskQoG0/
      create_home: no

  - name: creates a folder for the aforementioned user to be smb shared
    file:
      path: /smbcitsalud/kinesiologia
      owner: kinesiologia
      group: citsaludusers
      state: directory
      mode: 0770
      recurse: yes

  - name: creates a user for the department recursoshumanos
    user:
      name: recursoshumanos
      append: yes
      groups:
        - citsaludusers
      password: $6$3QM1d58jZv5q3pHp$Ose2JqAI4fuHzvOSrtQ10xyuDx1mNnFv.TSBA6p7qBMd0TBE7VG0XtpVF5PKraTkGgZq2ydnpYtIvACvXdEuT1
      create_home: no

  - name: creates a folder for the aforementioned user to be smb shared
    file:
      path: /smbcitsalud/recursoshumanos
      owner: recursoshumanos
      group: citsaludusers
      state: directory
      mode: 0770
      recurse: yes

  - name: creates a user for the company admin
    user:
      name: admin
      append: yes
      groups:
        - citsaludusers
      password: $6$C2tJ9A0k48V.Ula7$cVMaA64zdmy2AE.efJFdAF8qFCahh7Qu1msd6q5lTT8EUw863.V7/ZHb2IetOewLhqV5ortCkePRH5pPWA9yP0
      create_home: no

  - name: creates a folder for the aforementioned user to be smb shared
    file:
      path: /smbcitsalud/admin
      owner: admin
      group: citsaludusers
      state: directory
      mode: 0770
      recurse: yes

  - name: creates a user for techical support with sudo access
    user:
      name: soporte
      append: yes
      groups:
        - citsaludusers
        - sudo
      password: $6$G0TABL01gyipijbF$demVH8eo/Ofjoal1iUQPB7vv62LqlA2XVExwh4VfxThALWaoUa8bLqcYMlZctinbk49TyJRcZYLHdlMOsbV1r0
      create_home: yes
      shell: /bin/bash

  - name: creates a user for a guest
    user:
      name: invitado
      append: yes
      groups:
        - citsaludusers
      password: $6$4hd5VnPeOt2uRPsh$HNQWfX2JbzEFQ.bz/wTDXepASWw8ifycfjckKBnTEV1InFVHlwyNePBcYispjNHr.eqBFafFOsGOAynqXAUPb/
      create_home: no

  - name: adds the smb config
    copy:
      src: ./../../smb.conf
      dest: /etc/samba/smb.conf
      force: yes
      mode: 0644

  - name: restarts the samba service
    service:
      name: sshd
      enabled: yes
      state: restarted


